name: Push to master

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PKG_TOKEN }}

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  new-release:
    uses: victoryguide/vg-workflows/.github/workflows/new-release-npm.yaml@main
    needs: tests
    with:
      ref: "master"
    secrets:
      gha-pkg-token: ${{ secrets.GHA_PKG_TOKEN }}
